# -*- coding: utf-8 -*-
"""job.11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11MLrMXtHohhxHpxy_Qo3-lzgYj4iReWe
"""

# File: backend/fake_job_detector.py
# Member 4 - Fake Job Detector - JobGuard AI

import re

# ========== STEP 1: scam database ==========
# there are 4 types of scam

PAYMENT_SCAM_WORDS = [
    "registration fee", "security deposit", "pay money", "paytm karo",
    "upi payment", "processing fee", "refundable fee", "investment"
]

GUARANTEED_JOB_WORDS = [
    "guaranteed job", "100% job", "pakki naukri", "without interview",
    "bina interview ke", "earn daily", "daily 3000", "daily 5000", "work from home and earn"
]

CONTACT_SCAM_WORDS = [
    "telegram", "whatsapp only", "contact on whatsapp", "personal whatsapp",
    "inbox on telegram", "t.me/"
]

URGENCY_WORDS = [
    "urgent hiring", "join immediately", "today only", "last date today",
    "immediately join", "limited seats", "aaj hi join karo"
]

# ========== STEP 2: for checking scam we are using different function ==========

def check_payment_scam(text):
    reasons = []
    for word in PAYMENT_SCAM_WORDS:
        if word in text.lower():
            reasons.append(f"Paise maang raha hai -> '{word}'")
    return reasons

def check_guaranteed_claims(text):
    reasons = []
    for word in GUARANTEED_JOB_WORDS:
        if word in text.lower():
            reasons.append(f"Fake guarantee de raha hai -> '{word}'")
    return reasons

def check_suspicious_contact(text):
    reasons = []
    for word in CONTACT_SCAM_WORDS:
        if word in text.lower():
            reasons.append(f"Official email ki jagah Telegram/WhatsApp pe bula raha hai -> '{word}'")

    # UPI ID ya personal number ka pattern check
    upi_pattern = r"[a-zA-Z0-9.\-_]{2,256}@[a-zA-Z][a-zA-Z]{2,64}"
    if re.search(upi_pattern, text):
        reasons.append("Personal UPI ID se payment maang raha hai (Jaise tumhare screenshot me tha)")

    return reasons

def check_urgency_tactics(text):
    reasons = []
    for word in URGENCY_WORDS:
        if word in text.lower():
            reasons.append(f"Jaldi karne ka pressure bana raha hai -> '{word}'")
    return reasons

# ========== STEP 3: Main Function - Risk Score nikalega ==========

def analyze_job_risk(job_description):
    """
    Ye main function hai jo Member 1 call karega
    """
    all_reasons = []

    # Saare checks ko chalao
    all_reasons.extend(check_payment_scam(job_description))
    all_reasons.extend(check_guaranteed_claims(job_description))
    all_reasons.extend(check_suspicious_contact(job_description))
    all_reasons.extend(check_urgency_tactics(job_description))

    # Risk Score calculate karo
    # Har reason = 25 points. 4 reason mil gaye to 100% Fake
    risk_score = len(all_reasons) * 25
    if risk_score > 100:
        risk_score = 100

    # Risk Level Classify karo
    if risk_score == 0:
        risk_level = "Low Risk"
        result = "REAL"
    elif risk_score <= 50:
        risk_level = "Medium Risk"
        result = "SUSPICIOUS"
    else:
        risk_level = "High Risk"
        result = "FAKE"

    # Final Report banao
    final_report = {
        "result": result,
        "risk_score": risk_score,
        "risk_level": risk_level,
        "reasons": all_reasons if all_reasons else ["Koi scam ka sign nahi mila"]
    }

    return final_report

# ========== STEP 4: Testing ke liye ==========
if __name__ == "__main__":
    test_job = """
    Urgent hiring work from home job. Earn daily 5000.
    Contact on Telegram. Pay 60 rs registration fee on this UPI jaysawalanjana-1@okhdfcbank
    """

    report = analyze_job_risk(test_job)
    print(report)
    # Output ayega: {'result': 'FAKE', 'risk_score': 100, 'risk_level': 'High Risk', ...}